sudo: required
services:
        - docker
before_install:
        - docker build -t chhavisharma1997/docker-react -f Dockerile.dev .
script:
        - docker run chhavisharma1997/docker-react npm run test -- --coverage
