sudo: required
services:
        - docker
before_install:
        - docker build -t chhavisharma1997/docker-react -f Dockerfile.dev .
script:
        - docker run-e CI=true chhavisharma1997/docker-react npm run test -- --coverage
